version: '3.8'
include:
  - ./admin/service.yaml
  - ./client/services.yaml
services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=pt-BR
    volumes:
      - ./data:/var/lib/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  