version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:alpine
    networks:
     - app-lan
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=${DB_DATABASE:-optimus_admin_dev}
      - DB_USERNAME=${DB_USERNAME:-optimus}
      - DB_PASSWORD=${DB_PASSWORD:-optimus}
    volumes:
      - ./admin/resources/docker/init.db.sh:/docker-entrypoint-initdb.d/init.db.sh
    networks:
      - app-lan
  admin.fpm:
    container_name: admin.fpm
    image: devoptimus/admin-fpm
    environment:
      - APP_DEBUG=true
      - APP_ENV=local
    volumes:
      - ./admin/:/home/app/public_html
    networks:
      - app-lan
  admin.nginx:
    container_name: admin.nginx
    image: devoptimus/admin_nginx
    build:
      context: .
      target: admin_nginx
    ports:
      - 8015:80
    environment:
      - FPM_HOST="admin.fpm:9000"
    depends_on:
      - admin.fpm
    volumes:
      - ./admin/public:/home/app/public_html/public
    networks:
      - app-lan
  admin.frontend:
    container_name: admin.frontend
    image: devoptimus/admin_frontend
    build:
      context: .
      target: admin_frontend
    ports:
      - 3000:3000
    volumes:
      - ./admin:/home/app/public_html
      - ./admin/node_modules:/home/app/public_html/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - app-lan
  admin.cron:
    container_name: admin.cron
    image: devoptimus/admin_cron
    build:
      context: .
      target: admin_cron
    volumes:
      - ./admin:/home/app/public_html
    networks:
      - app-lan
networks:
  app-lan:
    
  