apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  APP_KEY: YmFzZTY0OkNqUjJWbjRVK0dUeXcrUEpLRTRhckNubWhGWk0xVldmbndHNTZ4cytSQk09Cg==
  DB_USERNAME: b3B0aW11cw==
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USERNAME_ROOT: cG9zdGdyZXM=
  DB_PASSWORD_ROOT: cGFzc3dvcmQ=
  REDIS_PASSWORD: bnVsbA==
