#!/usr/bin/env bash
set -eu

templates=$(ls /etc/nginx/template.d/*.template)

for file in $templates; do
    if [ -f "$file" ]; then
        config_file="/etc/nginx/vhost.d/"$(basename "${file%.*}.conf")
        envsubst < $file > $config_file
    fi
done

doas nginx