apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metal-lb
  namespace: metallb-system
spec:
  addresses:
    - 172.19.0.200-172.19.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
